[package]
name = "ml"
version = "0.0.2"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/IvanUkhov/ml"
homepage = "https://github.com/IvanUkhov/ml"
description = "ML."
